# Generated by Django 4.2.4 on 2023-08-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGGrid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Close'), (0, 'Open')])),
            ],
        ),
        migrations.CreateModel(
            name='KepcoSide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cb281', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cb281', to='app_service.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dc_dn_link_ds121', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_dn_link_ds121', to='app_service.equipment')),
                ('dc_dn_link_es121', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_dn_link_es121', to='app_service.equipment')),
                ('dc_dn_link_es122', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_dn_link_es122', to='app_service.equipment')),
                ('dc_up_link_ds111', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_up_link_ds111', to='app_service.equipment')),
                ('dc_up_link_es111', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_up_link_es111', to='app_service.equipment')),
                ('dc_up_link_es112', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_up_link_es112', to='app_service.equipment')),
                ('transformer_cb101', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_cb101', to='app_service.equipment')),
                ('transformer_cb102', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_cb102', to='app_service.equipment')),
                ('transformer_es101', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_es101', to='app_service.equipment')),
                ('transformer_es102', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_es102', to='app_service.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dg_grid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='app_service.dggrid')),
                ('kepco_side', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='app_service.kepcoside')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='app_service.station')),
            ],
        ),
        migrations.AddField(
            model_name='dggrid',
            name='cb181',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cb181', to='app_service.equipment'),
        ),
        migrations.AddField(
            model_name='dggrid',
            name='cb191',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cb191', to='app_service.equipment'),
        ),
    ]
