# Generated by Django 4.2.4 on 2023-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0003_alter_binary_data_cb101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_data',
            name='cb101',
            field=models.BooleanField(),
        ),
    ]
