# Generated by Django 4.2.4 on 2023-08-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0005_analog_data_alter_binary_data_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analog_data',
        ),
        migrations.DeleteModel(
            name='Binary_data',
        ),
    ]
