# Generated by Django 4.2.4 on 2023-09-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_modbusprotocolsideapoint_modbusprotocolsidebpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modbusprotocolsideapoint',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='modbusprotocolsidebpoint',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='modbusprotocolsidecpoint',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
