# Generated by Django 4.2.4 on 2023-09-04 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_rename_create_at_modbusprotocolsideapoint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modbusprotocolsideapoint',
            options={'verbose_name_plural': 'Modbus 프로토컬 사이드 A포인트'},
        ),
        migrations.AlterModelOptions(
            name='modbusprotocolsidebpoint',
            options={'verbose_name_plural': 'Modbus 프로토컬 사이드 B포인트'},
        ),
        migrations.AlterModelOptions(
            name='modbusprotocolsidecpoint',
            options={'verbose_name_plural': 'Modbus 프로토컬 사이드 C포인트'},
        ),
        migrations.CreateModel(
            name='ModbusRandomCpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.modbusprotocolsidecpoint')),
            ],
            options={
                'verbose_name_plural': 'Modbus C포인트 수집 데이터',
                'db_table': 'tb_ModbusRandom_C',
            },
        ),
        migrations.CreateModel(
            name='ModbusRandomBpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.modbusprotocolsidebpoint')),
            ],
            options={
                'verbose_name_plural': 'Modbus B포인트 수집 데이터',
                'db_table': 'tb_ModbusRandom_B',
            },
        ),
        migrations.CreateModel(
            name='ModbusRandomApoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.modbusprotocolsideapoint')),
            ],
            options={
                'verbose_name_plural': 'Modbus A포인트 수집 데이터',
                'db_table': 'tb_ModbusRandom_A',
            },
        ),
    ]
