# Generated by Django 4.2.4 on 2023-09-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_alter_modbusprotocolsideapoint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modbusrandomapoint',
            table='tb_Modbus_Random_A',
        ),
        migrations.AlterModelTable(
            name='modbusrandombpoint',
            table='tb_Modbus_Random_B',
        ),
        migrations.AlterModelTable(
            name='modbusrandomcpoint',
            table='tb_Modbus_Random_C',
        ),
    ]
