# Generated by Django 4.2.4 on 2023-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0007_remove_modbusrandombpoint_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_pollution_10', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('atmospheric_temperature', models.FloatField(null=True)),
                ('atmospheric_pressure', models.FloatField(null=True)),
                ('air_pollution_2', models.FloatField(null=True)),
                ('wind_direction', models.FloatField(null=True)),
                ('atmospheric_humidity', models.FloatField(null=True)),
                ('rainfall', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tb_environment',
            },
        ),
    ]
