# Generated by Django 4.2.4 on 2023-09-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_environmentaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='air_pollution_10',
            new_name='air_hum',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='air_pollution_2',
            new_name='air_press',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='atmospheric_humidity',
            new_name='air_tem',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='atmospheric_pressure',
            new_name='dust_10',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='atmospheric_temperature',
            new_name='dust_2',
        ),
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='wind_direction',
            new_name='wind_dir',
        ),
    ]
