# Generated by Django 4.2.4 on 2023-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0009_rename_air_pollution_10_environmentaldata_air_hum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaldata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
