# Generated by Django 4.2.4 on 2023-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0010_alter_environmentaldata_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentaldata',
            options={'verbose_name_plural': '환경데이터'},
        ),
    ]
