# Generated by Django 4.2.4 on 2023-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0011_alter_environmentaldata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalImageDataAlpha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_temp', models.FloatField(null=True)),
                ('min_temp', models.FloatField(null=True)),
                ('aver_temp', models.FloatField(null=True)),
                ('temp_dif', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': '열화상데이터 알파 point',
                'db_table': 'tb_tid_alpha',
            },
        ),
        migrations.CreateModel(
            name='ThermalImageDataBeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_temp', models.FloatField(null=True)),
                ('aver_temp', models.FloatField(null=True)),
                ('temp_dif', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': '열화상데이터 베타 point',
                'db_table': 'tb_tid_beta',
            },
        ),
        migrations.CreateModel(
            name='ThermalImageDataDelta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_temp', models.FloatField(null=True)),
                ('aver_temp', models.FloatField(null=True)),
                ('temp_dif', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': '열화상데이터 델타 point',
                'db_table': 'tb_tid_delta',
            },
        ),
        migrations.CreateModel(
            name='ThermalImageDataGamma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_temp', models.FloatField(null=True)),
                ('aver_temp', models.FloatField(null=True)),
                ('temp_dif', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': '열화상데이터 감마 point',
                'db_table': 'tb_tid_gamma',
            },
        ),
    ]
